// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/RomaBilka/BloGo/example-wire/internal/handlers"
	"github.com/RomaBilka/BloGo/example-wire/internal/repositories"
	"github.com/RomaBilka/BloGo/example-wire/internal/services"
)

// Injectors from wire.go:

func InitializeUserHttp(db *sql.DB) *handlers.UserHTTP {
	userRepository := repositories.NewPostgreUserRepository(db)
	userService := services.NewUserService(userRepository)
	userHTTP := handlers.NewUserHttp(userService)
	return userHTTP
}

func InitializeProductHttp(db *sql.DB) *handlers.ProductHTTP {
	productRepository := repositories.NewPostgreProductRepository(db)
	productService := services.NewProductService(productRepository)
	productHTTP := handlers.NewProductHttp(productService)
	return productHTTP
}
